#!/bin/sh

set -e
projectRoot="$(a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; cd "$a/../.." || return; pwd)"

# Set Docker/Kubernetes resource names managed by this script
containerName="ffc-demo-payment-service"
dockerPrefix="ffc-demo-payment"

(
  cd "${projectRoot}"

  kubectl delete job/ffc-demo-payment-service-migration

  helm delete --purge \
    ${dockerPrefix}-artemis \
    ${dockerPrefix}-postgres \
    ${containerName}
)
