#!/usr/bin/env sh

set -e
projectRoot="$(a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; cd "$a/.." || return; pwd)"

(
  cd "${projectRoot}"
  docker-compose exec ffc-demo-payment-service node ./test/send-test-message.js
)
