#!/usr/bin/env sh

set -e
projectRoot="$(a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; cd "$a/.." || return; pwd)"

# Check whether ffc-demo network needs creating
if [ -z "$(docker network ls --filter name=^ffc-demo$ --format={{.Name}})" ]; then
  echo "Creating ffc-demo network"
  docker network create ffc-demo
fi

(
  cd "${projectRoot}"
  docker-compose up --force-recreate $@
)
