#!/bin/bash
docker network inspect mine-support &>/dev/null || docker network create mine-support
docker-compose -f docker-compose.yaml -f docker-compose.local.yaml -v down
docker-compose -f docker-compose.yaml -f docker-compose.test.yaml -v down
docker-compose -f docker-compose.yaml -f docker-compose.local.yaml build --no-cache mine-support-payment-service
docker-compose -f docker-compose.yaml -f docker-compose.migrate.yaml up --force-recreate mine-support-payment-service
docker-compose -f docker-compose.yaml -f docker-compose.local.yaml up mine-support-payment-service
