#!/usr/bin/env sh

set -e
projectRoot="$(a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; cd "$a/.." || return; pwd)"

(
  cd "${projectRoot}"
  docker run -it -v "$(pwd)/test:/mine-support-payment-service/test" mine-support-payment-service npm run test
)
